### ISSUE TITLE
Now clear option

### ISSUE THREAD

**Issue by ggegoge** [chetmurthy/ledit#1]
I've been using ledit but it seems like there is no command that would work like ctrl-l in `rlwrap` or bash. I find it very useful to have the currently edited portion of text at the top rather than at the bottom of the terminal window + it gets messy so it is nice to clear it some times. Is there any option to get this sort of behaviour -- screen getting cleared and the line appearing at the top of it? From the manual it seems there is no key binding that would accomplish that but perhaps I'm mistaken

**Comment by chetmurthy** [comment]
I'm not the author of ledit, and the person who was the previous maintainer wasn't the author, either.  I'm just maintaining it, keeping it up-to-date with its prerequisites (e.g. camlp5) and will fix bugs.  Um .... if you have a PR, I'd be happy to have a careful look and then if it looks OK, merge it.  Would that be good for you?

P.S. To clarify: I don't use ledit.  I just want to make sure that it keeps working, as the libraries it depends-upon change.

**Comment by ggegoge** [comment]
Mostly I wanted to ask whether perhaps it is already possible but I just don't know how to do it but it doesn't seem to be the case. It seems like the only way would be indeed me writing a PR to address this issue. Unfortunately my command of OCaml regarding input/output management etc is insufficient so I don't think I could do that.

**Comment by chetmurthy** [comment]
I did a tiny bit of investigation into the ledit source.
1. it is written without using termcap/terminfo/curses
2. it only handles a single line (no wrapping)

So in short, it is very much "backlevel", and modernizing it would require a revamping of the code.  I don't think this is something I would want to undertake, not because it's hard (it isn't -- I've hacked on termcap-related stuff many times over the years) but because it doesn't seem like it has a big payoff.  It would be simpler to just use rlwrap.

I'm sorry, I'm just a maintainer of the current code, keeping it up-to-date with camlp5.

**Comment by chetmurthy** [comment]
To clearly see some of ledit's limitations, if you make your terminal window really large, then you'll find that (at least I did) ledit sticks to 80 columns (and no line-wrap).  I checked that "stty -a" said "177 columns", so it's not a terminal issue.
